# Generated by Django 3.0.6 on 2020-05-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200506_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='amount_in_kshs',
            new_name='enter_the_amount_to_be_transferred_in_KSHS',
        ),
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='recipient_account_no',
            new_name='enter_the_destination_account_number',
        ),
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='sender',
            new_name='enter_your_user_name',
        ),
    ]
